(ns advent-of-code.day-two-test
  (:require [clojure.test :refer :all]
            [clojure.data :refer :all]))

(def sample-input
  ["abcdef" "bababc" "abbcde" "abcccd" "aabcdd" "abcdee" "ababab"])

(def case-one-input ["bvhfawknyoqsudzrpgslecmtkj"
                     "bpufawcnyoqxldzrpgsleimtkj"
                     "bvhfawcnyoqxqdzrplsleimtkf"
                     "bvhoagcnyoqxudzrpgsleixtkj"
                     "bxvfgwcnyoqxudzrpgsleimtkj"
                     "bvqfawcngoqxudzrpgsleiktkj"
                     "bvhfawcnmoqxuyzrpgsleimtkp"
                     "bvheawcnyomxsdzrpgsleimtkj"
                     "bcdfawcnyoqxudzrpgsyeimtkj"
                     "bvhpawcnyoqxudzrpgsteimtkz"
                     "bxhfawcnyozxudzrpgsleimtoj"
                     "bvhfdwcnyozxudzrposleimtkj"
                     "bvpfawcnyotxudzrpgsleimtkq"
                     "bvhfpwccyoqxudzrpgslkimtkj"
                     "bvhfawcnyoqxudirpgsreimtsj"
                     "bvhfawcnyoqxudzppgbleemtkj"
                     "bvhzawcnyoqxudqrpgslvimtkj"
                     "bvhfawclyoqxudirpgsleimtka"
                     "bvhgawfnyoqxudzrpguleimtkj"
                     "bvhfazcnytqxudzrpgslvimtkj"
                     "bvhfawcnygxxudzrpgjleimtkj"
                     "bxhfawcnyoqxudzipgsleimtxj"
                     "bvhptwcnyoqxudzrpgsleimtmj"
                     "bzhfawcgyooxudzrpgsleimtkj"
                     "bvhjlwcnyokxudzrpgsleimtkj"
                     "bvhfawcnyoqxudbrmgslesmtkj"
                     "bvhfawcnysixudzwpgsleimtkj"
                     "bvhflwcnymqxxdzrpgsleimtkj"
                     "bvifawcnyoyxudzrpgsleimtvj"
                     "bvhfawcnyofxudlrpgsheimtkj"
                     "bvhbawcmyoqxudzrpggleimtkj"
                     "bhhxgwcnyoqxudzrpgsleimtkj"
                     "bvhfawgnyoqxbdzrpgsleimfkj"
                     "bvhfawcnyoqxudcrngsleimykj"
                     "bvhfawcnyofxudzrpgslebgtkj"
                     "bvhfaocnybqxudzapgsleimtkj"
                     "bvhxawcnyodxudzrpfsleimtkj"
                     "bchfawcnyoqxudrrtgsleimtkj"
                     "bvhfawcqyoqxudzdpgsltimtkj"
                     "bvhfawknyoqxudzrpnsleimtbj"
                     "cihfawcnyoqxudirpgsleimtkj"
                     "bvlfawpnyoqxudzrpgslgimtkj"
                     "bulfawcnyoqbudzrpgsleimtkj"
                     "bvhfajcnyoqkudzrpgsoeimtkj"
                     "bvhrakcnyoqxudzrpgsleimjkj"
                     "bvbftwcnyoqxuvzrpgsleimtkj"
                     "bvhfhwcnyoqxudzrpgslelmtbj"
                     "bvhyawcntoqxudzrpgsleimtuj"
                     "xvhuawcnyoqxuqzrpgsleimtkj"
                     "pvhfawcnyoqxudzdpglleimtkj"
                     "bvhfawsnyoqxudzrpgvlefmtkj"
                     "bvhfawcnyoqxudzrpgepeiwtkj"
                     "bvhfawcnyoqxudzrphsleittkr"
                     "dvhfawcnyoqxudzrpkslzimtkj"
                     "bvhfawpnyoqxudzrpgmlcimtkj"
                     "bvhsawcnyzqxudzrpgsaeimtkj"
                     "bdhfawcnyoqxudzrpasleiwtkj"
                     "bvhfawbnyoqxpdbrpgsleimtkj"
                     "mvhfawwnyoqxujzrpgsleimtkj"
                     "bvafawcnyoyxudzrpgsleidtkj"
                     "bvhyawcnyoqxudztpgzleimtkj"
                     "besfawcnyoqxudzrpgsleimdkj"
                     "bvhfawcnyoqxudrrpgsjeimjkj"
                     "xvhfkwcnyoqxudzcpgsleimtkj"
                     "bvhfawcnyeqdudzrpgzleimtkj"
                     "bvhfuwcnybqxudzrpgsleimttj"
                     "lvhfawcnyoqhudzdpgsleimtkj"
                     "bvhfawcnyoqxudzrpgslevwtnj"
                     "bvhfadcnzoqxxdzrpgsleimtkj"
                     "bvsfawcnyoqxpdzrpgileimtkj"
                     "bzhfaycnyoqxudzrpgsxeimtkj"
                     "bwhfdwcnyoqxudzrpgsleimtkz"
                     "bvhfawcnyoqxudzrpgsjlimtkm"
                     "bvhfawcnyoqxudsrwgsleimtlj"
                     "bbhfalynyoqxudzrpgsleimtkj"
                     "bvhfawcnyeqxudzrpglleimtkr"
                     "bvhfawnnboqxurzrpgsleimtkj"
                     "yvhfawcnyoqxudzrpgslzimtpj"
                     "bvhfjwcnyoqxqdxrpgsleimtkj"
                     "bthfawcnyoqfudzrpgslhimtkj"
                     "bvhfawchuoqxudzqpgsleimtkj"
                     "bvhfawcndoqxudzrugsleimrkj"
                     "bvhfawcnnoqxjdzrpgsleidtkj"
                     "bvhpawcnyoqkudzrpgsleimtzj"
                     "bvhfaiinyoqxudzopgsleimtkj"
                     "bvhfawcnyxqxuizrigsleimtkj"
                     "bvnfawcnyoqxudzqpgsleimbkj"
                     "bvnfawcnyoeyudzrpgsleimtkj"
                     "bvhfawcnyoqxudarpgsieimtoj"
                     "bthcawcnyoqxudlrpgsleimtkj"
                     "bvhfnwcnyozxudzrpgsleomtkj"
                     "bpwfawcnyoqxudzrpgskeimtkj"
                     "bvhfapcnyoqxudnrpgsxeimtkj"
                     "bvhfdwcnyoqxubzrxgsleimtkj"
                     "fvhfawcnyoqxjdzrpgsleirtkj"
                     "bvhfawcneoqxudzrvzsleimtkj"
                     "bvhaawcnyoqxudzrpgsleimtex"
                     "bvhfawcnyojxudvrpgsleimckj"
                     "bvlfawcnyoqxddzrpgsleimtko"
                     "bvhfawclfoqxudzrpgsleiktkj"
                     "bvhfawciyobxudzrpgkleimtkj"
                     "bvhfpwcnyoqxudzrpgsqeimtkd"
                     "bvhyawcnyyqxudzrkgsleimtkj"
                     "bvhfawcncoqxudzrphsaeimtkj"
                     "bvhfawmnyoqxudzrpgifeimtkj"
                     "bvhfawcjyoqxudzjpgszeimtkj"
                     "bohfawcnwoqxudzrpgsleimwkj"
                     "bvhfaucnyoqxudzrpgfluimtkj"
                     "bvhfawlnyoqgudzrpgwleimtkj"
                     "bmhfawcnyoqxndzrpgsleymtkj"
                     "bvhfawcngoqxudzrpzxleimtkj"
                     "bihfawcnyoqxudrrpgsleimokj"
                     "lvhfawcnylqxudzrpgsleintkj"
                     "bvhfawcnyoqvugzrqgsleimtkj"
                     "bvhfawcnyoqxudzgpgslqimtij"
                     "bvhfawcnyoqludzrpgslnimtcj"
                     "hvhfawcnyolxudzrpgsmeimtkj"
                     "nvhfawcdkoqxudzrpgsleimtkj"
                     "bvhfawcnyoqxkdzrggsneimtkj"
                     "bvhfawnnyoqxudzrpgqleibtkj"
                     "bvhfawyuyoqxudzrhgsleimtkj"
                     "wvhfbwcnyoqxtdzrpgsleimtkj"
                     "bvhfawcnyoqxedzzpgoleimtkj"
                     "bvhfawcnioqxunzrpgsleimtnj"
                     "bvhfawctyoqxudzrpgsldkmtkj"
                     "bvhfawcnyonxudzrpgsleitpkj"
                     "bvefawcnyoqaudzhpgsleimtkj"
                     "bvhfawcnyxqxudzrpgslelmbkj"
                     "bvhfamrnyoqxudzrpgsleimgkj"
                     "bvhfaqcnyoqxudzrpgsaeimekj"
                     "bvhfawcnyoqcidzrpgsleimvkj"
                     "bvhfawcnnorxudzrpgsmeimtkj"
                     "bvroawcnyoqxudzrpgsleiwtkj"
                     "bvhfwwcnyoqxudzrpaslewmtkj"
                     "bvsfawcnyoqxudzcpgszeimtkj"
                     "bkhfmwcnyoqjudzrpgsleimtkj"
                     "bvtfawcnyoqxudzrcgslecmtkj"
                     "bvhfawcnypzxudzrpgsleimtkv"
                     "bvhfawcnyoqzudzrfgtleimtkj"
                     "bvhpawcnyoqxudhrpgsleimtko"
                     "tvhfawcnyoqxudzxpfsleimtkj"
                     "bvhfawccyofxudzrpqsleimtkj"
                     "bvnfawtnyoqxuzzrpgsleimtkj"
                     "bvhfamcnuwqxudzrpgsleimtkj"
                     "bvhfawcfyoqxudjrpgsleimrkj"
                     "bvhpalcnyoqxudzrpgslexmtkj"
                     "bvhfawcnjsqxudzlpgsleimtkj"
                     "bvhfafcnioqxydzrpgsleimtkj"
                     "bvzfawcnyxqxudzgpgsleimtkj"
                     "bvhzawcnyoqxudzrpgslewctkj"
                     "bvhiawcnhoqrudzrpgsleimtkj"
                     "bvhfawcnyoqxuszrggslenmtkj"
                     "bvhfowcnyoqxudzrptseeimtkj"
                     "behfawfnyoqxudzrpgsleimlkj"
                     "lvhfawcnyoqxudsrpgvleimtkj"
                     "bvhfawnnyaqxudzrpgsqeimtkj"
                     "lvhfawcnfoqxvdzrpgsleimtkj"
                     "svhxawcnyoqxudzrpqsleimtkj"
                     "bvhfawqnfoqxudzrpgsleimkkj"
                     "bvhfafcnyoqcudzrpgsleimtcj"
                     "bvhfyfcntoqxudzrpgsleimtkj"
                     "bvhfpwcnyoqxudzrpgsleimumj"
                     "bvhfawccyoqxudzrqgrleimtkj"
                     "bvhfawqnyoqxudzbpgsleimkkj"
                     "bvhflwcnyoqxudzrpxsleemtkj"
                     "bvhfawcnyoqxuezrpgslehrtkj"
                     "bvhfawceyoqxudzrpgsleimswj"
                     "bvhfawcncohgudzrpgsleimtkj"
                     "bahfawcnyoqxgdzrpgsleamtkj"
                     "yvhfawcnyoqxudzrppslrimtkj"
                     "fvhfawcmyoqxudzrpgskeimtkj"
                     "bvylawsnyoqxudzrpgsleimtkj"
                     "bvhfswcnyyqxedzrpgsleimtkj"
                     "fvrfawcnyoqxudzrpgzleimtkj"
                     "bvhfawcnyoqxuvzrpgslermtks"
                     "bvhkawccyoqxudzcpgsleimtkj"
                     "bvhfaobnyoqxudzrprsleimtkj"
                     "bvbfawcnyoqxudirpgsleimhkj"
                     "bvhfawcnyoqxudzvpgsueimtgj"
                     "bvhxawcnyoqxudzrpgsleimtgi"
                     "svhfawcjyoqxuszrpgsleimtkj"
                     "bvnfawcnyoeyudzrpgsldimtkj"
                     "bvhfawcnyoqxuhzrpgsleimcki"
                     "bvhfvwcnyoqxudzizgsleimtkj"
                     "bvhfapznyohxudzrpgsleimtkj"
                     "bvhfaelnyosxudzrpgsleimtkj"
                     "xvhfawcnmoqxuhzrpgsleimtkj"
                     "bjhfawcnyaqxutzrpgsleimtkj"
                     "bvhfawcnyohxudzrpgslgnmtkj"
                     "bvhfawcnyoqxudzrppsreimtkx"
                     "fvhfapcnyoqyudzrpgsleimtkj"
                     "qvhfafcnyoqxudorpgsleimtkj"
                     "bvhfawcnyoqxedzrwgsleimtvj"
                     "bvhfawgnyoqxudzupgqleimtkj"
                     "bvhfowctyoqxudzrpgbleimtkj"
                     "bvhwawcnyoqxudzapgslvimtkj"
                     "bvhfadcnyoqxudzrugsleimtuj"
                     "bvhfawcnyosxudzlpgsleamtkj"
                     "bvhfawcnywqxuqzrpgsloimtkj"
                     "bvhfawcnyoqxumzrpgvlfimtkj"
                     "bvhfawcgyoqxbdzrpgsleomtkj"
                     "bvhfahcnyoqwudzrfgsleimtkj"
                     "gvbfawcnyrqxudzrpgsleimtkj"
                     "svhfawcnyoqxudlrpgsleimtkx"
                     "avhfafcnyoqxuhzrpgsleimtkj"
                     "bvhfawcsyoqxuazrpgsleimtej"
                     "bvofawcnyoqxudzrpgsteimtkf"
                     "bvhfajcnyoqxudzqpgszeimtkj"
                     "bvhfawcsyoqxudzrmgsleiktkj"
                     "mvhfawcnyoqxudzrpgkluimtkj"
                     "bvhfawcnhoqxudzrpgslwhmtkj"
                     "bmhaawsnyoqxudzrpgsleimtkj"
                     "bvhfawcnyoqxudzhpgsleimhyj"
                     "bvhfxwcnyoqxsdzypgsleimtkj"
                     "bvhpawcyyoqxuczrpgsleimtkj"
                     "bvomawcnyovxudzrpgsleimtkj"
                     "bvhfawcnjvqxudzrpgsleimtkt"
                     "nvhfawcnyqqxudzrpgsleittkj"
                     "bvhiawcnyzqxudzrpysleimtkj"
                     "bvhdawcnyoqxukzrpgsleimtuj"
                     "bvhfawcnyyxxudzrpgslzimtkj"
                     "hvhfawcnyoqxudzupgslemmtkj"
                     "byhfawknyoqxudzrpgsleimtkb"
                     "bvhfawcnyoqxudzrpasleihakj"
                     "bvafahcnyaqxudzrpgsleimtkj"
                     "bkhfawcnyoqxudzrpgllepmtkj"
                     "bghfawcnycqxuzzrpgsleimtkj"
                     "bvhfawcnyoqxudzrbgeleimtkl"
                     "bvhfascnyoqgudzrpgsveimtkj"
                     "bvhfawnnyoqxudzrpgsleimtdl"
                     "bvhqawcnyoqxudzrpgsleimgrj"
                     "bvhsawdwyoqxudzrpgsleimtkj"
                     "bvhfawcnyoqxudzrpgaleipttj"
                     "bvhfawcnrlqxudzrbgsleimtkj"
                     "bvhfdwcnyoqxudzqpcsleimtkj"
                     "bvhfawcnyoqxudzopgslexmokj"
                     "bvhfawcoyoqxudzrpghlewmtkj"
                     "bvhfozcnykqxudzrpgsleimtkj"
                     "bvhfawcnyoqxuvzrpgslrimtkr"
                     "bvhfrncnyoqrudzrpgsleimtkj"
                     "bvhfawcnyocxuizrpgslefmtkj"
                     "bvhfawywyoqxudzrpgsleimxkj"
                     "bvhfawcnyoqxugzrpgslrimtij"
                     "bvtfawcnyoqxudzcpgsleimtfj"
                     "bvhfawcnyoqxuzzspgsleimtkz"
                     "bvhfawcnzoqxvdzrpgslsimtkj"
                     "bvhfzwcnyoqxudzrpgslenmhkj"
                     "bvhfkccnyoqxudzrpgzleimtkj"
                     "bvhfawcnyoqzudzrpgslhimwkj"
                     "bzhfawvnyooxudzrpgsleimtkj"])

(defn contains-same-letter-n-times [input n]
  (let [chars (seq (char-array input))
        counts (vals (frequencies chars))]
    (some #(= n %) counts)))

(defn contains-same-letter-twice [input]
  (contains-same-letter-n-times input 2))

(defn contains-same-letter-three-times [input]
  (contains-same-letter-n-times input 3))


(defn get-checksum [input]
  (let [contains-twice (filter contains-same-letter-twice input)
        contains-three-times (filter contains-same-letter-three-times input)]
    (* (count contains-twice) (count contains-three-times))))

(deftest contain-same-letter-exactly-twice
  (testing "does not contain same letter exactly twice in string"
    (is (not (contains-same-letter-twice "abcdef"))))
  (testing "contains the same letter twice"
    (is (contains-same-letter-twice "bababc")))
  (testing "contains the same letter twice"
    (is (not (contains-same-letter-twice "abcccd")))))


(deftest contain-same-letter-exactly-three-times
  (testing "does not contain same letter exactly twice in string"
    (is (not (contains-same-letter-three-times "abcdef"))))
  (testing "contains the same letter twice"
    (is (contains-same-letter-three-times "bababc")))
  (testing "contains the same letter twice"
    (is (contains-same-letter-three-times "abcccd"))))

(deftest checksum
  (testing "checksum of given sample"
    (is (= 12 (get-checksum sample-input))))
  (testing "checksum of case one"
    (is (= 6696 (get-checksum case-one-input)))))

(defn check-difference-pair [a b]
  (let [difference (diff (seq (char-array a)) (seq (char-array b)))
        non-nil-diff (map #(remove nil? %) difference)]
    (and (= 1 (count (first non-nil-diff))) (= 1 (count (second non-nil-diff))))))

(deftest find-difference
  (testing "finds difference pair of strings"
    (is (check-difference-pair "fghij" "fguij"))
    (is (not (check-difference-pair "abcde" "axcye")))))